In [1]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [2]:
from tensorflow.keras.datasets import imdb

In [3]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [5]:
X_train[:2]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

#### The text data is already in vector form. So we dont need to do any embedding

In [6]:
y_train[:2]

array([1, 0])

The y data is in already label encoded.
1--> Bad Review
0--> Good Review

In [26]:
import numpy as np

In [27]:
def vector_seq(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results

In [28]:
#X_train = vector_seq(X_train)
X_test = vector_seq(X_test)

In [7]:
X_train[:2]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [8]:
#As the dataset has different lengths, we will do padding

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
X_train_padded = pad_sequences(X_train, padding='post', maxlen=100)     # Not giving maxlen argument, It will automatically create padding taking the
                                                            # maxlen of largest array

In [10]:
X_train_padded[:2]

array([[1415,   33,    6,   22,   12,  215,   28,   77,   52,    5,   14,
         407,   16,   82,    2,    8,    4,  107,  117, 5952,   15,  256,
           4,    2,    7, 3766,    5,  723,   36,   71,   43,  530,  476,
          26,  400,  317,   46,    7,    4,    2, 1029,   13,  104,   88,
           4,  381,   15,  297,   98,   32, 2071,   56,   26,  141,    6,
         194, 7486,   18,    4,  226,   22,   21,  134,  476,   26,  480,
           5,  144,   30, 5535,   18,   51,   36,   28,  224,   92,   25,
         104,    4,  226,   65,   16,   38, 1334,   88,   12,   16,  283,
           5,   16, 4472,  113,  103,   32,   15,   16, 5345,   19,  178,
          32],
       [ 163,   11, 3215,    2,    4, 1153,    9,  194,  775,    7, 8255,
           2,  349, 2637,  148,  605,    2, 8003,   15,  123,  125,   68,
           2, 6853,   15,  349,  165, 4362,   98,    5,    4,  228,    9,
          43,    2, 1157,   15,  299,  120,    5,  120,  174,   11,  220,
         175,  136,   5

In [11]:
len(X_train[1]), len(X_train_padded[0])

(189, 100)

In [12]:
X_test_padded = pad_sequences(X_test, padding='post', maxlen=100)

In [13]:
len(X_test_padded[152])

100

## Building Model

In [14]:
from tensorflow.keras.layers import LSTM, Dense, Flatten, Embedding
from tensorflow.keras.models import Sequential

In [15]:
vocab_size=10000
embed_size=128

In [16]:
model = Sequential()
model.add(Embedding(vocab_size, output_dim=128, input_shape=(100,) ) )
model.add(LSTM(60, activation='tanh'))
#model.add(Flatten())

model.add(Dense(1, activation='sigmoid'))

#model.summary()

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 128)          1280000   
                                                                 
 lstm (LSTM)                 (None, 60)                45360     
                                                                 
 dense (Dense)               (None, 1)                 61        
                                                                 
Total params: 1,325,421
Trainable params: 1,325,421
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',
              loss = tf.keras.losses.binary_crossentropy,
              metrics=['accuracy'])

In [19]:
X_train_padded

array([[1415,   33,    6, ...,   19,  178,   32],
       [ 163,   11, 3215, ...,   16,  145,   95],
       [1301,    4, 1873, ...,    7,  129,  113],
       ...,
       [  11,    6, 4065, ...,    4, 3586,    2],
       [ 100, 2198,    8, ...,   12,    9,   23],
       [  78, 1099,   17, ...,  204,  131,    9]], dtype=int32)

In [21]:
hist = model.fit(X_train_padded, y_train, epochs=10, batch_size=128)

Epoch 1/10
196/196 [==============================] - 5s 28ms/step - loss: 0.2682 - accuracy: 0.8935
Epoch 2/10
196/196 [==============================] - 5s 27ms/step - loss: 0.1981 - accuracy: 0.9258
Epoch 3/10
196/196 [==============================] - 5s 26ms/step - loss: 0.1510 - accuracy: 0.9468
Epoch 4/10
196/196 [==============================] - 5s 26ms/step - loss: 0.1093 - accuracy: 0.9622
Epoch 5/10
196/196 [==============================] - 5s 26ms/step - loss: 0.0939 - accuracy: 0.9693
Epoch 6/10
196/196 [==============================] - 5s 25ms/step - loss: 0.0693 - accuracy: 0.9781
Epoch 7/10
196/196 [==============================] - 5s 25ms/step - loss: 0.0460 - accuracy: 0.9864
Epoch 8/10
196/196 [==============================] - 5s 24ms/step - loss: 0.0567 - accuracy: 0.9809
Epoch 9/10
196/196 [==============================] - 4s 23ms/step - loss: 0.0446 - accuracy: 0.9865
Epoch 10/10
196/196 [==============================] - 4s 22ms/step - loss: 0.0320 - accura

In [22]:
X_test_padded.shape

(25000, 100)

In [29]:
model.evaluate(X_test, y_test)

ValueError: ignored

In [38]:
y_train = np.asarray(y_train).astype('float32')
y_test = y_test.reshape(25000,1)

In [39]:
y_test.shape

(25000, 1)