In [2]:
!pip install transformers

     |████████████████████████████████| 3.4 MB 4.1 MB/s 
     |████████████████████████████████| 3.3 MB 29.2 MB/s 
     |████████████████████████████████| 895 kB 51.0 MB/s 
     |████████████████████████████████| 596 kB 46.3 MB/s 
     |████████████████████████████████| 67 kB 5.1 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [7]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

By default, the model downloaded for this pipeline is called “distilbert-base-uncased-finetuned-sst-2-english”.

In [10]:
text = ["I am very happy learnning NLP",
        "HuggingFace is good platform to get models and preprocessor for NLP",
        "I am exahausted, NLP is not an easy thing to learn",
        "Today India team played very bad cricket",
        "I would love to go Himalayas"]
classifier(text)

[{'label': 'POSITIVE', 'score': 0.9998341798782349},
 {'label': 'POSITIVE', 'score': 0.9990234375},
 {'label': 'NEGATIVE', 'score': 0.9993366599082947},
 {'label': 'NEGATIVE', 'score': 0.9993879795074463},
 {'label': 'POSITIVE', 'score': 0.9988141059875488}]

In [11]:
# Using a new model
model1 = pipeline('sentiment-analysis', model='finiteautomata/bertweet-base-sentiment-analysis')

Downloading:   0%|          | 0.00/890 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/515M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/295 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/824k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/17.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

emoji is not installed, thus not converting emoticons or emojis into text. Please install emoji: pip3 install emoji


In [12]:
model1(text)

[{'label': 'POS', 'score': 0.9920077323913574},
 {'label': 'POS', 'score': 0.914578378200531},
 {'label': 'NEG', 'score': 0.747325599193573},
 {'label': 'NEG', 'score': 0.9835637807846069},
 {'label': 'POS', 'score': 0.9835822582244873}]

## We can use AutoTokenizer and TFAutoModelForSequenceClassification to prepare data and to embed the data

In [15]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

In [17]:
model = 'distilbert-base-uncased-finetuned-sst-2-english'
tokenizer = AutoTokenizer.from_pretrained(model)
model2 =  TFAutoModelForSequenceClassification.from_pretrained(model)

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.

All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [18]:
text0 = "It is sad that we can not go for the movie"
tokens = tokenizer(text0)

In [21]:
tokens

{'input_ids': [101, 2009, 2003, 6517, 2008, 2057, 2064, 2025, 2175, 2005, 1996, 3185, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

### You can pass a list of sentences directly to your tokenizer. If your goal is to send them through your model as a batch, you probably want to pad them all to the same length, truncate them to the maximum length the model can accept and get tensors back

In [22]:
text

['I am very happy learnning NLP',
 'HuggingFace is good platform to get models and preprocessor for NLP',
 'I am exahausted, NLP is not an easy thing to learn',
 'Today India team played very bad cricket',
 'I would love to go Himalayas']

In [26]:
tf_batch = tokenizer(text,
                     padding=True,
                     truncation=True,
                     max_length=512,
                     is_split_into_words=False,
                     return_tensors='tf')

In [33]:
for key, value in tf_batch.items():
  print(f'{key}: {value.numpy().tolist()}')

input_ids: [[101, 1045, 2572, 2200, 3407, 4553, 5582, 17953, 2361, 102, 0, 0, 0, 0, 0, 0, 0, 0], [101, 17662, 12172, 2003, 2204, 4132, 2000, 2131, 4275, 1998, 17463, 3217, 9623, 21748, 2005, 17953, 2361, 102], [101, 1045, 2572, 4654, 23278, 19966, 2098, 1010, 17953, 2361, 2003, 2025, 2019, 3733, 2518, 2000, 4553, 102], [101, 2651, 2634, 2136, 2209, 2200, 2919, 4533, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 1045, 2052, 2293, 2000, 2175, 26779, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


#### Once your input has been preprocessed by the tokenizer, you can send it directly to the model.

In [34]:
tf_output = model2(tf_batch)

#### In 🤗 Transformers, all outputs are objects that contain the model’s final activations along with other metadata.

In [36]:
tf_output

TFSequenceClassifierOutput([('logits',
                             <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
                             array([[-4.183078 ,  4.5212584],
                                    [-3.4240937,  3.506406 ],
                                    [ 4.023486 , -3.2941225],
                                    [ 4.0418735, -3.3563657],
                                    [-3.2661989,  3.4698136]], dtype=float32)>)])

#### Let’s apply the SoftMax activation to get predictions.

In [38]:
import tensorflow as tf
tf_predictions = tf.nn.softmax(tf_output.logits, axis=-1)

In [39]:
tf_predictions

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1.6583753e-04, 9.9983418e-01],
       [9.7655738e-04, 9.9902344e-01],
       [9.9933666e-01, 6.6330715e-04],
       [9.9938798e-01, 6.1195530e-04],
       [1.1859643e-03, 9.9881411e-01]], dtype=float32)>

In [45]:
[tf.argmax(i).numpy() for i in tf_predictions]

[1, 1, 0, 0, 1]

In [ ]:
input = tokenizer(text0)
tf_output = model2(input, labels=tf.constant([1,0]))
tf_output

In [52]:
tf.constant([[1,0],[1,0],[1,0]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [1, 0]], dtype=int32)>

In [57]:
# Saving the model

tokenizer.save_pretrained('./tf_save_pretrained')
model2.save_pretrained('./tf_save_pretrained')

In [ ]:
from transformers import TFAutoModel
pt_save_directory = './tf_save_pretrained'
tokenizer = AutoTokenizer.from_pretrained(pt_save_directory)
tf_model = TFAutoModel.from_pretrained(pt_save_directory, from_pt=True)

# Sequence Classification

In [99]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf

In [114]:
classes = ['Not Paraphrase', 'Is Paraphrase']

sentence0 = 'I am doing phd in physics in University of Hyderabad'
sentence1 = 'Today, there is a cricket match between India and SouthAfrica'
sentence2 = 'University of Hyderabad has a wide range of courses and curricular activities'
sentence3 = "Currently, I am doing research in physics"

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased-finetuned-mrpc')
tf_model = TFAutoModelForSequenceClassification.from_pretrained('bert-base-cased-finetuned-mrpc')

# The tokenizer will automatically add any model specific separators (i.e. <CLS> and <SEP>) and tokens to
# the sequence, as well as compute the attention masks.

paraphrase_token = tokenizer(sentence0, sentence3, return_tensors='tf')
not_paraphrased_token = tokenizer(sentence1, sentence2, return_tensors='tf')

Some layers from the model checkpoint at bert-base-cased-finetuned-mrpc were not used when initializing TFBertForSequenceClassification: ['dropout_183']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at bert-base-cased-finetuned-mrpc.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [108]:
# getting result by giving tokens(preprocessed texts) to the model
paraphrase_result = tf_model(paraphrase_token)

#Getting probabilities after TF softmax transformation. This gives a TF tensor, so convetring it to 2D numpy array
paraphrase_prob = tf.nn.softmax(paraphrase_result.logits, axis=1).numpy().tolist()[0]
paraphrase_prob

[0.10767778009176254, 0.8923222422599792]

In [112]:
# Should be paraphrased
for i in range(len(classes)):
  print(f"{classes[i]}: {round(paraphrase_prob[i]*100,2)}%")

Not Paraphrase: 10.77%
Is Paraphrase: 89.23%


In [121]:
# getting result by giving tokens(preprocessed texts) to the model
not_paraphrased_result = tf_model(not_paraphrased_token)

#Getting probabilities after TF softmax transformation. This gives a TF tensor, so convetring it to 2D numpy array
not_paraphrased_prob = tf.nn.softmax(not_paraphrase_results).numpy()
not_paraphrased_prob

array([0.7154102 , 0.28458983], dtype=float32)

In [123]:
# Should not be paraphrased
for i in range(len(classes)):
  print(f"{classes[i]}: {round(not_paraphrased_prob[i]*100,2)}%")

Not Paraphrase: 71.54%
Is Paraphrase: 28.46%


# Summarization

In [131]:
from transformers import pipeline

summarizer = pipeline('summarization')
# defaulted to sshleifer/distilbart-cnn-12-6 (https://huggingface.co/sshleifer/distilbart-cnn-12-6)

ARTICLE = """ New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
2010 marriage license application, according to court documents.
Prosecutors said the marriages were part of an immigration scam.
On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18.
"""

#Because the summarization pipeline depends on the PreTrainedModel.generate() method, we can override the default arguments
# of PreTrainedModel.generate() directly in the pipeline for max_length and min_length as shown below.

print(summarizer(ARTICLE, max_length=150, min_length=30, do_sample=False))

No model was supplied, defaulted to sshleifer/distilbart-cnn-12-6 (https://huggingface.co/sshleifer/distilbart-cnn-12-6)


[{'summary_text': ' Liana Barrientos, 39, is charged with two counts of "offering a false instrument for filing in the first degree" In total, she has been married 10 times, with nine of her marriages occurring between 1999 and 2002 . At one time, she was married to eight men at once, prosecutors say .'}]


In [125]:
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

In [127]:
# Here we are using Google T5 model, one can also use bart
tokenizer = AutoTokenizer.from_pretrained('t5-base')
tf_model = TFAutoModelForSeq2SeqLM.from_pretrained('t5-base')

Downloading:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/773k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/851M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [132]:
# T5 uses a max_length of 512 so we cut the article to 512 tokens.
input_text = tokenizer('Suummary text: '+ARTICLE, return_tensors='tf', max_length=512)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [136]:
# Generating output 
output = tf_model.generate(input_text['input_ids'], max_length=150, min_length=30, do_sample=False, early_stopping=True, 
                           num_beams=4, length_penalty=0.2)

In [143]:
# The output is the token ids of texts, decoding it using tokenizer.decode
tokenizer.decode(output.numpy()[0])

'<pad> False omissions: false statements on marriage license application. pleaded not guilty at State Supreme Court in the Bronx.'

## Summerization using bart

In [173]:
# import and initialize the tokenizer and model from the checkpoint
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

#checkpoint = "eugenesiow/bart-paraphrase"
checkpoint = 't5-base'

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

In [179]:
input_token = tokenizer(ARTICLE, max_length=512, return_tensors='tf')

In [180]:
#input_text['input_ids']

In [189]:
output = tf_model.generate(input_token['input_ids'], max_length=150, min_length=30, num_beams=4, length_penalty=0.2, early_stopping=True)

In [193]:
tokenizer.decode(output.numpy()[0])

'<pad><extra_id_0> five more times, sometimes within two weeks of each other. Then, 18 days later, she got hitched again in the Bronx. In 2010, she married again, but without divorcing her first husband. The marriages were part of an immigration scam, prosecutors say.'

# Translation

In [198]:
from transformers import pipeline
translator = pipeline("translation_en_to_de")
translator("Hugging Face is a technology company based in New York and Paris")

No model was supplied, defaulted to t5-base (https://huggingface.co/t5-base)


[{'translation_text': 'Hugging Face ist ein Technologieunternehmen mit Sitz in New York und Paris.'}]

### Using t5 base

In [202]:
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM
model = TFAutoModelForSeq2SeqLM.from_pretrained('t5-base')
tokenizer = AutoTokenizer.from_pretrained('t5-base')

All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [203]:
tokenizer.model_max_length

512

In [213]:
inputs = tokenizer("Translate English to German: Hugging Face is a technology company based in New York and Paris", return_tensors='tf')

In [214]:
outs =  model.generate(inputs['input_ids'], max_length=40, num_beams=4, early_stopping=True)

In [212]:
tokenizer.decode(outs.numpy()[0])

'<pad> Hugging Face ist ein Technologieunternehmen mit Sitz in New York und Paris.'